### ISSUE TITLE
Missing Clusterrole and ClusterRoleBinding for kube-chorus-router

### ISSUE THREAD

**Issue by l4z41** [citrix/citrix-k8s-node-controller#6]
Missing ClusterRole and ClusterRoleBinding if the Node Controller is creating the `kube-chorus-router` pods and sa in `kube-system` namespace. Should be documented that this will be created and namespace should be configurable

```
Error from server (Forbidden): configmaps "kube-chorus-router" is forbidden: User "system:serviceaccount:kube-system:kube-chorus-router" cannot get resource "configmaps" in API group "" in the namespace "kube-system"
```

**Comment by l4z41** [comment]
Reference found here: https://github.com/Chorusio/kube-chorus-router/blob/master/deploy/k8s-router.yaml

```
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: kube-chorus-router
rules:
  - apiGroups: ["*"]
    resources: ["nodes", "configmaps", "pods", "namespaces", "serviceaccounts", "clusterroles", "clusterrolebindings"]
    verbs: ["get", "list", "watch", "create", "patch", "delete", "update"]

  - apiGroups: [""]
    resources: ["nodes", "configmaps", "pods", "namespaces", "serviceaccounts", "clusterroles", "clusterrolebindings"]
    verbs: ["get", "list", "watch", "create", "patch", "delete", "update"]

  - apiGroups: ["extensions"]
    resources: ["pods", "configmaps", "serviceaccounts", "ingresses/status"]
    verbs: ["get", "list", "watch", "create"]
```

```
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: kube-chorus-router
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-chorus-router
subjects:
- kind: ServiceAccount
  name: kube-chorus-router
  namespace: default
apiVersion: rbac.authorization.k8s.io/v1
```
